graphics/darktable: fix build on powerpc64le
Disable including gdkcolor.h because pixel is a type on POWER:
/usr/local/include/gtk-3.0/gdk/deprecated/gdkcolor.h:56:11: error: two or more data types in declaration specifiers
   56 |   guint32 pixel;

Disable OpenCL:
/wrkdirs/usr/ports/graphics/darktable/work/darktable-3.4.1/data/kernels/bilateral.cl:67:17: error: implicit declaration of function 'atom_add' is invalid in OpenCL
    old_val.i = atom_add(ival, 0);

Approved by:	tier 2 blanket