graphics/libgphoto2: fix build on GCC architectures
Use C11 compiler:
checking for libltdl flags... set explicitly: -I/usr/local/include -L/usr/local/lib -lltdl

Switch to C99:
docupen/calibration.c:31:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   31 |  for (unsigned int i = 0; i < sizeof(struct lut); i++) {
      |  ^~~