graphics/mesa-devel: split VKLAYERS from VULKAN after r566607
VULKAN was overloaded to include Vulkan drivers and layers. However,
building layers requires at least one Vulkan driver.

$ make showconfig
[...]
     VULKAN=on: Vulkan layers: device-select,overlay
[...]
====> Vulkan layers: device-select,overlay
     anv=on: Haswell and newer
     radv=on: Southern Islands and newer (implies LLVM)

$ make clean all WIHOUT="anv radv"
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: bin/mesa-overlay-control.py
Error: Missing: lib/libVkLayer_MESA_device_select.so
Error: Missing: lib/libVkLayer_MESA_overlay.so
Error: Missing: share/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json
Error: Missing: share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json
===> Error: Plist issues found.
*** Error code 1

PR:		253741