emulators/qemu-utils: unbreak after r553312
Due to many breaking changes temporarily switch to qemu42.

===>  Applying extra patch files/patch-configure
1 out of 2 hunks failed--saving rejects to configure.rej
===>  Applying extra patch files/patch-Makefile
2 out of 3 hunks failed--saving rejects to Makefile.rej
ERROR: unknown option --disable-bluez
strip: open ../stage/usr/local/bin/qemu-* failed: No such file or directory

PR:		252498