science/netcdf: move byteswap4 and byteswap8 fuctions higher so that they are declared when necessary
dfilter.c:366:2: warning: implicit declaration of function 'byteswap4' is invalid in C99 [-Wimplicit-function-declaration]
        byteswap4(mem); /* step 1: byte-swap each piece */
        ^
dfilter.c:368:2: warning: implicit declaration of function 'byteswap8' is invalid in C99 [-Wimplicit-function-declaration]
        byteswap8(mem); /* step 2: convert to little endian format */
        ^
dfilter.c:370:2: warning: implicit declaration of function 'byteswap8' is invalid in C99 [-Wimplicit-function-declaration]
        byteswap8(mem); /* step 1: convert to little endian format */
        ^
dfilter.c:371:2: warning: implicit declaration of function 'byteswap4' is invalid in C99 [-Wimplicit-function-declaration]
        byteswap4(mem); /* step 2: byte-swap each piece */
        ^
dfilter.c:681:1: error: static declaration of 'byteswap8' follows non-static declaration
byteswap8(unsigned char* mem)
^
dfilter.c:368:2: note: previous implicit declaration is here
        byteswap8(mem); /* step 2: convert to little endian format */
        ^
dfilter.c:700:1: error: static declaration of 'byteswap4' follows non-static declaration
byteswap4(unsigned char* mem)
^
dfilter.c:366:2: note: previous implicit declaration is here
        byteswap4(mem); /* step 1: byte-swap each piece */
        ^
4 warnings and 2 errors generated.