devel/libuinputplus: Fix QA issues
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: libdata/pkgconfig/uInputPlus.pc
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

http://package21.nyi.freebsd.org/data/114amd64-default-qat/566258/logs/errors/libuinputplus-0.1.4_1.log